;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
; background = ${xrdb:color0:#222}
; background = #000000f9
; background-alt = #000000c9
; foreground = ${xrdb:color7:#222}
; foreground = #94a7d4
foreground-alt = ${xrdb:color5:#4e576e}
background = ${xrdb:color0:#21252e}
foreground = ${xrdb:color7:#94a7d4}
primary = ${xrdb:color1:#BF616A}
secondary = ${xrdb:color3:#BF616A}
alert = #bd2c40

[bar/example]
;monitor = ${env:MONITOR:HDMI-1}
enable-ipc=true
width = 100%
height = 27
offset-x = 0%
offset-y = 0%
radius = 0
fixed-center = true                   
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #f00

border-size = 1
border-color = #00000000

padding-left = 1
padding-right = 1
module-margin-left = 1
module-margin-right = 1

font-0 = CodeNewRoman Nerd Font:style=Regular:size=11:scale=7;2
;font-0 = Noto Serif Ahom:style=Regular:scale=12;3
font-1 = Noto Color Emoji:fontformat=truetype:size=8:antialias=false;0
;font-2 = siji:pixelsize=10;3

modules-left = bspwm i3 xwindow
;  ^^^ Note: Only one WM module (bspwm or i3) will be active depending on session.
modules-center = mpd
; modules-right = filesystem alsa pulseaudio xkeyboard memory cpu wlan eth battery temperature date powermenu
modules-right = filesystem pulseaudio xkeyboard memory cpu eth sticky-note picom bt bt100 redshift date powermenu 

tray-position = right
tray-padding = 2
;tray-background = #0063ff

wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

scroll-up = bspwm-deskprev
scroll-down = bspwm-desknext

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-padding = 2

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
; format-prefix-underline = ${colors.secondary}
label-layout = %layout%
; label-layout-underline = ${colors.secondary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}


[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground}


[module/bspwm]
type = internal/bspwm
label-focused = %name%
label-focused-background = ${colors.background}
label-focused-underline= ${colors.primary}
label-focused-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-1 = 
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1
; Separator in between workspaces
; label-separator = |


[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = true
; Only show workspaces on the same output as the bar
pin-workspaces = true
label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}
; focused = Active workspace on focused monitor
label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2
; unfocused = Inactive workspace on any monitor
label-unfocused = %name%
label-unfocused-padding = 2
; visible = Active workspace on unfocused monitor
label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
; urgent = Workspace with urgency hint set
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2
; Separator in between workspaces
; label-separator = |




[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>
icon-prev = 玲
icon-stop = 栗
icon-play = 契
icon-pause = 
icon-next = 怜
label-song-maxlen = 25
label-song-ellipsis = true



[module/xbacklight]
type = internal/xbacklight
format = <label> <bar>
label = BL
bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}


[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight


[module/cpu]
type = internal/cpu
interval = 15
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #f90000
label = %percentage:2%%


[module/memory]
type = internal/memory
interval = 60
format-prefix = "﬙ "
format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #4bffdc
label = %percentage_used%%


[module/wlan]
type = internal/network
interface = wlp1s0f0u9
interval = 3.0
format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %{A1:nm-applet &:} %essid%%{A}
format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}





[module/eth]
type = internal/network
interface = enp3s0
interval = 3.0
format-connected-underline = #A3BE8C
format-connected-prefix = ""
format-connected-prefix-padding = 1
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %downspeed%
; format-disconnected =
format-disconnected = <label-disconnected>
format-disconnected-underline = #BF616A
format-disconnected-prefix = ""
format-disconnected-prefix-padding = 1
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}



[module/date]
type = internal/date
interval = 60
date = "%h/%d"
date-alt = "%Y/%h/%d"
time = " %H:%M"
time-alt = " %H:%M:%S"
format-prefix =""
format-prefix-padding = 0.5
format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #0a6cf5
label = %time% %date% 
; label-padding = 1


[module/pulseaudio]
type = internal/pulseaudio
foreground=${colors.foreground}
sink = alsa_output.pci-0000_12_00.3.analog-stereo
use-ui-max = true
interval = 5
format-volume = <ramp-volume> <label-volume>
label-muted =  
label-muted-foreground = #666
ramp-volume-0 = 
ramp-volume-0-foreground = #fc4e03
ramp-volume-1 = 奔
ramp-volume-1-foreground = #fc9403
ramp-volume-2 = 墳
ramp-volume-2-foreground = #fcba03
ramp-volume-3 = 
ramp-volume-3-foreground = #98fc03
click-right = pavucontrol



[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/redshift]
type = custom/ipc
format-prefix = " "  
hook-0= ". ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh temperature "
hook-1 = ". ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh toggle "
hook-2 = ". ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh increase"
hook-3 = ". ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh decrease"
click-left = "#redshift.hook.1"
scroll-up = "#redshift.hook.2"
scroll-down = "#redshift.hook.3"
initial=1

[module/bt]
type = custom/text
content = ""  
click-left = "ddcutil setvcp 10 + 20"
click-right = "ddcutil setvcp 10 - 20"

[module/bt100]
type = custom/text
content = "100/0"  
click-left = "ddcutil setvcp 10 100"
click-right = "ddcutil setvcp 10 0"

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu
expand-right = true
format-spacing = 1
label-open = 
label-open-foreground = ${colors.foreground-alt}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}
menu-0-0 = reboot
menu-0-0-exec = loginctl reboot
menu-0-1 = power off
menu-0-1-exec =loginctl poweroff
menu-0-2 = Sleep
menu-0-2-exec =loginctl suspend
menu-0-3 = Logoff
menu-0-3-exec =loginctl terminate-user void
menu-1-0 = cancel
menu-1-0-exec = menu-open-0

[settings]
screenchange-reload = true
; compositing-background = xor
; compositing-background = screen
; compositing-foreground = source
; compositing-border = over
pseudo-transparency = true

[global/wm]
margin-top = 0
margin-bottom = 0
; vim:ft=dosini

[module/picom]
type=custom/text
click-left="~/.config/picom/toggle.sh"
format= <label>
content= " "

[module/sticky-note]
type=custom/text
click-left="~/.config/kitty/toggle_sticky_note.sh"
format= <label>
content= " "
