#! /bin/bash
bspc rule -r  "*"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     嗢  -

bspc config border_width  2 
#. "${HOME}/.cache/wal/colors.sh"
if [[ -f "${HOME}/.config/bspwm/bspwm_colors.sh" ]]
then
    . "${HOME}/.config/bspwm/bspwm_colors.sh"
fi

# bspc config focus_follows_pointer true
bspc config top_padding        30
bspc config bottom_padding     10
bspc config left_padding       20
bspc config right_padding      20 
bspc config window_gap          20
bspc config normal_border_color "#242410"



bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius 35

bspc config pointer_motion_interval 20
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


#AutoStart
$HOME/.config/polybar/launch.sh & disown
setxkbmap -option grp:alt_space_toggle us,ar &
#xfce4-power-manager --daemon &  disown
nm-applet &  disown
mpd & disown
dunst & disown
pgrep -x "xfce-polkit" > /dev/null && echo "POLKIT RUNNING" || /usr/libexec/xfce-polkit & disown ;
wpg -s $( realpath /home/void/.config/wpg/.current) & disown
# /usr/bin/emacs --daemon &  disown
# gamemoded & disown
# /home/void/.config/wal/launch.sh /usr/share/void-artwork/desktop.png &
# albert &
# /home/void/.config/bspwm/bspwm_colors.sh &bash /home/void/.config/bspwm/bspwm_colors.sh &  disown




#Workspaces
# . "./workspaces/workspace_rules.sh" & disown
bspc rule -a Gimp desktop='^8' state=floating follow=on


# Workspace 2
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a "Brave-browser-nightly" desktop='^2'

# Workspace 3
bspc rule -a "Code - OSS" desktop='^3' follow=on
bspc rule -a "Emacs" desktop='^3' follow=on
bspc rule -a "Sublime_text" desktop='^3' follow=on
bspc rule -a "sublime_text" desktop='^3' follow=on
bspc rule -a "sticky_note" state=floating sticky=on focus=on rectangle=400x400+100+100

# Workspace 4
bspc rule -a '@joplinapp-desktop' desktop='^4' follow=on
bspc rule -a 'Joplin' desktop='^4' follow=on
bspc rule -a 'XpdfReader' desktop='^4' follow=on
bspc rule -a "Evince" desktop='^4' follow=on

# Workspace 5
bspc rule -a "vlc" desktop='^5' follow=on

# Workspace 6
bspc rule -a "Steam" desktop='^6' follow=on
bspc rule -a "Epic Games Launcher" desktop='^6' follow=on
bspc rule -a "steam_app_0" desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Kupfer.py focus=on

#AutoStart
#. "./autostart" & disown


# remove border from un-focused windows
# Slow
# while bspc subscribe -c 1 node_focus; do
#    bw="$(bspc config border_width)"
#    bspc config border_width "$bw"
#    bspc config -n focused border_width "$((bw + 1))"
# done
